### ISSUE TITLE
Refine the script grouping logic

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#112]
* [ ] be careful with the grouping. I think we actually want some fairly nuanced logic on how we group which might mean we end up explicitly storing a 'group by' value in the db to make it easy. for example
    * [ ] most scripts we will group by just their raw script with no params
    * [ ] in select cases we will group by the full url including all params, but with redacted values so just the param keys. 
    * [ ] eg plugin files are very useful to be grouped by their component and area which are path info AND query params
    * [ ] much more advanced case which we will deal with later is cron where we will break up a single long running cron cli into multiple profiles one for each task being run. (Don't stress about this now but worth having it in the back of your mind a a use case)

**Comment by jaypha** [comment]
I propose having a user setting for the scripts that are grouped with pathinfo etc. The scripts that would need this would vary from installation to installation depending on plugins installed and site usage.
