### ISSUE TITLE
Should we suspend profiling while doing a partial save?

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_excimer#116]
At the moment, for regular profiling, when doing a  partial save, we grab the profile logs on the fly. According to the documentation, continuing profiling while doing this could cause interference.
See https://github.com/wikimedia/php-excimer/blob/8dd7a62856866f942b52733d7a7075242ce5483e/stubs/ExcimerProfiler.php#L87.

**Comment by brendanheywood** [comment]
Possibly if this turns out to be a recurring bug then yes lets do this

**Comment by jaypha** [comment]
Since this issue was raised, the code has been refactored. The function getLog() is no longer called. On each interval, the code always calls flush(). Therefore this issue is no longer relevant.
