### ISSUE TITLE
Add a quick summary to the performance check

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#139]
This should be a cheap check, mostly just links to the reports.

The summary could show the consistently slowest web script, or maybe the top 3

This should be ok if nothing slow, and probably a warn or info for slow things. It should not be an error

**Comment by jaypha** [comment]
To clarify, this refers to Site Admin -> Reports -> Performance overview, and the Check API?

**Comment by brendanheywood** [comment]
correct
