### ISSUE TITLE
Profile stored under wrong request url and status looked ok

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#142]
I'm not quite sure what actually triggered this profile, but I didn't directly visit the error page. I think this was reloading the admin page during an upgrade during maintenence mode, which then loads the error page.

![image](https://user-images.githubusercontent.com/187449/148727876-5f26cece-d29c-40cb-abec-e3210c7b3032.png)

So 2 things weird:
* [ ] the request is not the page I was on, so its pulling this from the wrong place or getting corrupted somehow
* [ ] the status was 200 which wasnt the case, it was a 503 or 50x

**Comment by jaypha** [comment]
I have not been successful in reproducing this error. As for the code, I looked at the source for error/index.php, and it only sets the code to 404, and only if the 'code=404' parameter is set. Otherwise the code remains 200.

**Comment by keevan** [comment]
@brendanheywood Not sure if you have the profile and the relevant profile data (e.g. stack trace) which might be useful? Potentially it might be another task (e.g. adhoc) that was fired off but failed? (Goes through passthru and might not be logged under the same parent profile) Just theorizing.

**Comment by brendanheywood** [comment]
One way to reproduce:

http://moodle.local/crap

and you need to have error pages setup:

https://docs.moodle.org/dev/Error_pages

It probably needs to grab the raw url which is in the browser and not the url which comes out of the moodle api at a guess

**Comment by macgirvin** [comment]
It isn't obvious from the above doco how to setup error pages to reproduce this. I've tried clearing the doc root and "open in new window" from /admin/settings.php?section=documentation but neither or both of these are providing an error page or an excimer profile.
