### ISSUE TITLE
Split index into page of all profiles, and then details page which loads profile by record id

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#16]

**Comment by jaypha** [comment]
Can you clarify, do you mean for the profile graph to be on a different URL to the summary table?
Thanks.

**Comment by brendanheywood** [comment]
I simply mean an index.php page which lists all of the profiles in a table, and then you drill down into a detail page (eg profile.php) which has the flamegraph on it given a single profile id. The current index.php combines both functionally and is a bit of a mish mash, so this issue was kinda half done already I'd just prefer it cleaner in two files
