### ISSUE TITLE
Add a watch user mode

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#20]
This would be similar to the PROFILEALL mode but is trigger session by session and turned on when a userid / username / email hits one of a specific set of values in a textarea. Possibly also trigger it when any user hits a specific page and from then on

* [  ] store the username for the current user
* [  ] store the session id - partially redacted

**Comment by jaypha** [comment]
So I understand, you currently want userid, username, email and url for triggers. Any others (for now)?
Do you always want the profiling to last for the remainder of the session?
Do you want to be able to combine triggers? e.g. certain user hits a certain url?
Thanks

**Comment by brendanheywood** [comment]
This issue is only a single trigger which is FLAMEALL. It will have the same usage as tool_profiling and FLAMEME, ie it will flip a bit in your session and continuously profile everything in this and future requests until you do FLAMEALLSTOP as a query param

We may add other triggers later such as triggering depending on who the user is, or what script etc, but thats out of scope for this issue.

The existing code is already recording the redacted session id, can you please also record the userid of the logged in user as well. That actually independent of this new trigger and should apply across the board

**Comment by jaypha** [comment]
I think I get it. Someone uses FLAMEALL as a param, then it profiles until FLAMEALLSTOP as a PARAM. Ok?

Actually, the whole session ID is recorded, but redacted on display. I can change it do store it redacted if you want.

**Comment by brendanheywood** [comment]
Correct

Lets split that into https://github.com/catalyst/moodle-tool_excimer/issues/43
