### ISSUE TITLE
Unit tests should not mess up other plugins

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#242]
Bunch of errors like: Unexpected DB writes in phpunit_util::reset_all_data()

I'm ok with excimer not running inside other unit tests. Not sure how to make it run inside it's own tests.

But first rule is do no harm so lets get it working asap and then figure out the second part as we need to

**Comment by keevan** [comment]
Also unit test failure related:

https://github.com/catalyst/moodle-tool_excimer/runs/6362440697?check_suite_focus=true

It seems this line might need to be updated to cater for a new default value.
https://github.com/catalyst/moodle-tool_excimer/blob/d6e652a/tests/tool_excimer_manager_test.php#L43

**Comment by jaypha** [comment]
It looks like the offending code is this. https://github.com/catalyst/moodle-tool_excimer/blob/7db8575705f15f6dc0d7971df690612be6e3ac47/settings.php#L130-L137. Would this also turn it on for unit testing? If so, then yes, this is the culprit.

The Eximer plugin testing code runs various parts of the code explicitly, so it does not need auto profiling.
