### ISSUE TITLE
Excimer isn't correctly including the time waiting for a session lock

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#244]
This is hard, because we are relying on the _after_config hook and this delay is in the session manager before this hook is called.

It gives misleading numbers on pages where there could be say a 10 second delay waiting and then 1 second of processing, and excimer shows it as just one second. 

I think at minimum lets try and infer the time the script started and just show this in the profile metadata even if it isn't in the flame graph.

The tideways profiler is hard coded to allow it to kick off much earlier:
https://github.com/moodle/moodle/blob/master/lib/setup.php#L442

A proper solution might be:
* [x] land this tracker: https://tracker.moodle.org/browse/MDL-75014
* [ ] document backporting that + patch in ci for this plugin
* [ ] start excimer in that callback

Good test is using this:
https://master.localhost/admin/tool/sessionbreaker/

**Comment by brendanheywood** [comment]
Maybe just here:
https://github.com/moodle/moodle/blob/master/lib/setup.php#L799

and call it _before_session_start

**Comment by brendanheywood** [comment]
https://tracker.moodle.org/browse/MDL-75014

**Comment by brendanheywood** [comment]
https://tracker.moodle.org/browse/MDL-75014 has landed in core

**Comment by jaypha** [comment]
This tracker has been backported to all versions of Moodle back to 3.5, and Totara 16, 13 & 12.
