### ISSUE TITLE
Reshuffle tabs and groupings of scripts / tasks / cli / ws

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#247]
Thinking that we want 2 main high level tabs both of which are grouped by script:

* [x] Slowest web pages
* [x] Slowest CLI / tasks / WS
* [x] Both of them then drill down into a list of N profiles for that script

**Comment by jaypha** [comment]
Want do you want done with Recent and Unfinished?

**Comment by brendanheywood** [comment]
Leave them as is. Recent is still useful. Unfinished I don't think has ever worked properly but that's out of scope for this issue

**Comment by brendanheywood** [comment]
So the clarify this further, if you start on the 'Slowest web pages' you see the scripts, then you click on a script to see the profiles for that script and you should still be on the 'Slowest web pages' tab. Same goes for 'Slow CLI / tasks / WS'.

Also thinking of a better a name, thinking 'Slowest requests' or even just 'Slow requests'
