### ISSUE TITLE
Auto break cron cli into each cron task and profile individually

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#25]
We probably don’t care about the cron system itself. We care about auto profile for each task boundary. It's not immediately clear if we can cut this cleanly, but we could at minimum detect the stack trace and track it back to the cron function calls and detect if the task has changed and slice it after the fact. This means the cut point won't be perfect but it's only within the precision of a simple sample so perfectly fine.

* [ ] new set of config for minimum task length

**Comment by jaypha** [comment]
We can find specific tasks by looking for a *::execute sample that is a child of cron_run_inner_scheduled_task().
We cannot determine the run time exactly, but we can say that the time is between N*P and (N+1)*P, where N is the number of samples collected and P is the sampling period (if N=1, there is no lower time limit). So it might make sense to have the config check for minimum number of samples found.

**Comment by brendanheywood** [comment]
Yeah in practice we are worrying about tasks that take hours so some rounding at the ms level is not important.

The logic looks good, it will need a tweak to support adhoc tasks too. You can exit the logic early by making sure we are either in a CLI or /admin/cron.php

**Comment by jaypha** [comment]
Because this is a complicated issue. I'm going to put it on the back burner for the christmas period and work on some of the more trivial ones.
