### ISSUE TITLE
Breakdown of all requests and histograms of duration with totals

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#250]
We want to be able to see a list of all the worst pages, independent of whether they have profiles or not. In order to do this efficiently we want to have probabilistic counting for all numbers involved so that the io is log(n) as you scale.

https://en.wikipedia.org/wiki/Approximate_counting_algorithm

The end result is a table where we can see:
* [ ] a list of all of the urls by 'group' - the same grouping where we strip off params
* [x] these will need to become first class records one per group
* [x] we will have a fuzzy count of how many hits this url group has had
* [x] we will have a fuzzy breakdown count of how many took 1 sec, 2 second, 4 second etc
* [ ] we now we can calculate percentiles and averages and histograms
* [x] we can integrate them to come up with 'seconds spent serving page X' and then store this number itself too
* [x] make all of these numbers normalized to a month, just reset them each month
* [ ] or better yet can we hold this month and last month? the pro rata days in this month against last month

**Comment by jaypha** [comment]
I've been thinking. Why do we need a fuzzy count? Why not a regular count? And for times, why not keep a running sum?

**Comment by brendanheywood** [comment]
That is the most important question you could ask, and the answer is: [Design principle 1: Do no harm](https://github.com/catalyst/moodle-tool_excimer#1-do-no-harm)

If we counted every single one then we would have to do a DB write per page, and not just a db write but also lots of contention writing to the same table on every single request and on big sites this is many millions of requests per day.

By using probabilistic counting if we do a 1,000,000 requests on the same page then instead of 1000000 db updates we do a grand total of 20 writes. The DB load using this method is O(log(n)) instead of O(n). From a business point of view we do not need an exact count, all we need is very rough figures, knowing it is between 500k and 1000k requests is enough. And for a large site under heavy load excimer should be the faintest shadow of extra load on the system.

In practice we are counting a few more things so the writes will be higher but they are still O(log(n))
