### ISSUE TITLE
Redact web service tokens in urls

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#280]
* [ ] POST webservice/rest/server.php?wstoken=xxxxxxxx&wsfunction=

Have a scan through some prod sites access logs and look for other things we should redact

* [ ] ?key=xx
* [ ] ?token=xxx

**Comment by jaypha** [comment]
I found a couple: 'authtoken' and 'key'. I was thinking maybe add a setting so that extra ones can be set for a site without needing to update the code.

**Comment by brendanheywood** [comment]
+1 for a setting
