### ISSUE TITLE
tool_excimer_after_config exception

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-tool_excimer#296]
Moodle 3.11 latest
Excimer latest

Exception calling 'tool_excimer_after_config'
line 49 of /admin/tool/excimer/classes/web_processor.php: call to tool_excimer\manager->get_starttime()
line 131 of /admin/tool/excimer/classes/manager.php: call to tool_excimer\web_processor->init()
line 51 of /admin/tool/excimer/lib.php: call to tool_excimer\manager->start_processor()
line 1064 of /lib/setup.php: call to tool_excimer_after_config()
line 192 of /config.php: call to require_once()
line 6 of /admin/upgradesettings.php: call to require_once()

**Comment by jaypha** [comment]
The fix for #262 broke all versions before 4.1.

**Comment by jaypha** [comment]
Because the call to tool_excimer_before_session_start() isn't being done, the manager is not setup properly, so the crash occurs.

**Comment by brendanheywood** [comment]
@jaypha / @petersistrom can you please gracefully fix this in code, this came up in code review but fell through the cracks:

https://github.com/catalyst/moodle-tool_excimer/pull/262/files#r967772505

If before_session_start doesn't exist it should gracefully behave exactly as it did before

**Comment by brendanheywood** [comment]
Fixed
