### ISSUE TITLE
Database schema mismatch in Totara

### ISSUE THREAD

**Issue by matthewhilton** [catalyst/moodle-tool_excimer#298]
This seems to be a regression of https://github.com/catalyst/moodle-tool_excimer/issues/236 but only in Totara

Reproduce:
- Install Totara 12 with postgresql
- Install tool_excimer
- Run `admin/cli/check_database_schema.php`

You will get
```
-------------------------------------------------------------------------------
tool_excimer_profiles
 * column 'flamedatad3' is not expected (B)
 * column 'memoryusagedatad3' is not expected (B)
-------------------------------------------------------------------------------
```

The schema check fails, despite the plugin just being installed so there is something mismatched between probably the binary type and/or the length.

It might also be T12's `check_database_schema.php` being outdated, not sure.

**Comment by matthewhilton** [comment]
Seems to be https://tracker.moodle.org/browse/MDL-73095 not being included in T12

**Comment by jaypha** [comment]
Closing this as it is not directly relevant to this project.
