### ISSUE TITLE
make top level admin report which shows the list of profiles

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#3]
Use table lib:

https://docs.moodle.org/dev/lib/tablelib.php

**Comment by nigelchapman-catalyst** [comment]
I'm having to move across to metabase work, so this is minimal for now. (No tablelib.) 

![image](https://user-images.githubusercontent.com/46659321/123604168-efa36680-d83d-11eb-9ef2-6082c88d5026.png)
