### ISSUE TITLE
Unit test issue Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#316]
There was 1 error:

1) core\session_redis_test::test_normal_session_read_only
PHPUnit\Framework\Exception: PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/site/admin/tool/excimer/classes/manager.php on line 264
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/site/admin/tool/excimer/classes/manager.php on line 265
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /var/www/site/admin/tool/excimer/classes/manager.php on line 266

**Comment by bwalkerl** [comment]
Closing this off as it was fixed a long time ago as part of https://github.com/catalyst/moodle-tool_excimer/pull/309
