### ISSUE TITLE
add support for phpunit and behat

### ISSUE THREAD

**Issue by ewallah** [catalyst/moodle-tool_excimer#32]
Initializing and running PHPUnit and Behat tests only works after a minor modification to the function is_cli():

`        return PHPUNIT_TEST OR defined('BEHAT_SITE_RUNNING') OR php_sapi_name() === 'cli';
`

**Comment by jaypha** [comment]
I don't think this applies anymore. PHPUnit works fine. There are no Behat tests, and any function 'is_cli()' has long been removed.

**Comment by ewallah** [comment]
Indeed the problems in PHPunit and Behat are gone, but now I get database errors when running phpdoc.
