### ISSUE TITLE
dml_read_exception when reading from non-existent mdl_tool_excimer_profiles table

### ISSUE THREAD

**Issue by Fragonite** [catalyst/moodle-tool_excimer#330]
In some cases the `mdl_tool_excimer_profiles` table might not exist before `profile_helper.php` runs, which can result in the above exception.

This is happening when the database is being refreshed.

**Comment by Fragonite** [comment]
This issue can be closed. It turns out the problem that prompted the creation of this issue was related to Moodle MUC which was causing other problems too.

**Comment by brendanheywood** [comment]
Ok closing this
