### ISSUE TITLE
page group logic doesn't condense urls 

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#335]
For example lots of urls like this should be grouped under the same group but are not, which results in extra records for no reason:

```
tokenpluginfile.php/x/825079/mod_forum/xxx
tokenpluginfile.php/x/2353026/mod_forum/xxx
tokenpluginfile.php/x/640029/mod_forum/xxx
```

Roughly, anything which looks like a number should be redacted from the url as a starting point

**Comment by bwalkerl** [comment]
The changes made in #338 should have covered the extra ids slipping through in tokenpluginfile and a handful of variable param names.

Did we want to look into any further grouping here?

**Comment by brendanheywood** [comment]
Good for now, we will likely make more related issues down the track
