### ISSUE TITLE
Defer the data writes (eg via an SQS)

### ISSUE THREAD

**Issue by golenkovm** [catalyst/moodle-tool_excimer#340]
During peak loads or performance degradation the plugin may add its own extra load writing heaps of data for slow pages to the DB. This is to elaborate the options this could be mitigated. For example we discussed to backlog all the data in a SQS and then upload the data later via cron.
Also there were some thought on not profiling slow pages that are already in progress of profiling. But this could be a separate issue if needed.
Please feel free to edit the issue description if needed.

**Comment by brendanheywood** [comment]
As discussed not keen on this at all, the real issue is fixed and closing this as a won't do
