### ISSUE TITLE
Latest Upgrade takes forever 

### ISSUE THREAD

**Issue by aspark21** [catalyst/moodle-tool_excimer#352]
Had to run this from cli and upgrade is taking over 1h30m so far and no sign of completing. (Update : 3.5h and not complete, will let it run overnight just to see if it can even complete)

This is wild. Maybe this needs to purge historicaldata before upgrading?

MySQL 
Moodle4.4.2+

**Comment by brendanheywood** [comment]
fyi @bwalkerl

**Comment by aspark21** [comment]
In the end it ran for 6 hours and the GitHub actions runner I was using timed out.

It seems like it did complete the upgrade step for that instance though.

No way I can justify that much downtime for this in prod.

**Comment by brendanheywood** [comment]
thanks @aspark21 - yes thats obviously not acceptable, even 1 minute I think would be too much for what this is really needing to do conceptually. We will rewrite this upgrade step in pure sql. I'm away the next couple days but I've queued this up with top priority

**Comment by keevan** [comment]
Hi Alistair (@aspark21),

I've pushed a patch to hopefully resolve your performance issues. It's undergoing review at the moment, locally it does run slightly faster, though I don't have a good sample to test it against. 

Would you be able to give it a test and let us know if it helps?

If it's _still_ taking too long, it would be good to know some more details on your `tool_excimer_page_groups` table to try and get a better replication, e.g. the number of records, count of duplicates it had to deal with, etc.

**Comment by aspark21** [comment]
I can confirm it only took 85 seconds now. Thanks @keevan
