### ISSUE TITLE
Issue installing clean

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#36]
$ php admin/cli/uninstall_plugins.php --plugins=tool_excimer --run
Uninstalling: tool_excimer	Excimer sampling profiler
-->tool_excimer
++ XMLDB has detected one CHAR NOT NULL column (sessionid) with '' (empty string) as DEFAULT value. This type of columns must have one meaningful DEFAULT declared or none (NULL). XMLDB have fixed it automatically changing it to none (NULL). The process will continue ok and proper defaults will be created accordingly with each DB requirements. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed. ++
* line 1696 of /lib/datalib.php: call to debugging()
* line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
* line 255 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
* line 359 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
* line 543 of /lib/xmldb/xmldb_table.php: call to xmldb_field->arr2xmldb_field()
* line 276 of /lib/xmldb/xmldb_structure.php: call to xmldb_table->arr2xmldb_table()
* line 172 of /lib/xmldb/xmldb_file.php: call to xmldb_structure->arr2xmldb_structure()
* line 153 of /lib/xmldb/xmldb_file.php: call to xmldb_file->arr2xmldb_structure()
* line 291 of /lib/ddl/database_manager.php: call to xmldb_file->loadXMLStructure()
* line 369 of /lib/adminlib.php: call to database_manager->delete_tables_from_xmldb_file()
* line 246 of /lib/adminlib.php: call to drop_plugin_tables()
* line 1521 of /lib/classes/plugin_manager.php: call to uninstall_plugin()
* line 167 of /admin/cli/uninstall_plugins.php: call to core_plugin_manager->uninstall_plugin()
++ XMLDB has detected one CHAR NOT NULL column (sessionid) with '' (empty string) as DEFAULT value. This type of columns must have one meaningful DEFAULT declared or none (NULL). XMLDB have fixed it automatically changing it to none (NULL). The process will continue ok and proper defaults will be created accordingly with each DB requirements. Please fix it in source (XML and/or upgrade script) to avoid this message to be displayed. ++
* line 1696 of /lib/datalib.php: call to debugging()
* line 352 of /lib/xmldb/xmldb_object.php: call to xmldb_debug()
* line 255 of /lib/xmldb/xmldb_field.php: call to xmldb_object->debug()
* line 359 of /lib/xmldb/xmldb_field.php: call to xmldb_field->setDefault()
* line 543 of /lib/xmldb/xmldb_table.php: call to xmldb_field->arr2xmldb_field()
* line 276 of /lib/xmldb/xmldb_structure.php: call to xmldb_table->arr2xmldb_table()
* line 172 of /lib/xmldb/xmldb_file.php: call to xmldb_structure->arr2xmldb_structure()
* line 153 of /lib/xmldb/xmldb_file.php: call to xmldb_file->arr2xmldb_structure()
* line 416 of /lib/adminlib.php: call to xmldb_file->loadXMLStructure()
* line 374 of /lib/adminlib.php: call to get_used_table_names()
* line 246 of /lib/adminlib.php: call to drop_plugin_tables()
* line 1521 of /lib/classes/plugin_manager.php: call to uninstall_plugin()
* line 167 of /admin/cli/uninstall_plugins.php: call to core_plugin_manager->uninstall_plugin()
++ Success ++

**Comment by jaypha** [comment]
Should be fixed as part of issue 6 WIP.
