### ISSUE TITLE
Render a single profile as a flame graph

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#5]

**Comment by brendanheywood** [comment]
I'd be tempted for mvp to just use the cdn version of this and not bundle it:

https://github.com/spiermar/d3-flame-graph#jsdelivr-cdn

**Comment by nigelchapman-catalyst** [comment]
Works well for now. 

![image](https://user-images.githubusercontent.com/46659321/122533874-59b15400-d065-11eb-833c-cd6d00ffbf1c.png)

**Comment by nigelchapman-catalyst** [comment]
This now displays single profiles. I haven't moved this ticket up for code review, however, as I think that to be useful a single profile graph should be adding up total elapsed milliseconds in each function (even if approximate) rather than total number of calls to that function.
