### ISSUE TITLE
Store and expose the size in kb of the saved profile data

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#53]
Check if we actually need both the flamedata and the flamedatad3, maybe we can ditch one or the other

Primary reason we want this is to help tune other things like the number of samples, and the sampling throttle rate, min run time etc

**Comment by jaypha** [comment]
flamedatad3 is needed to generate the actual graph. If we don't keep it then it will need to be regenerated every time. We don't currently use flamedata, and it should be possible to reconstruct it if needed.
I put it in there against future need. It can be ditched if it never actually gets used.

**Comment by jaypha** [comment]
It's basically the same data in different formats.

**Comment by brendanheywood** [comment]
The other thing that would be good to have pulled out into a new field is the number of samples we have stored

**Comment by jaypha** [comment]
- [ ] numsamples field.

**Comment by jaypha** [comment]
Do you want numsamples and/or datasize shown in the profile table?

**Comment by brendanheywood** [comment]
Show on detail page but not on the high level page
