### ISSUE TITLE
Cosmetic random bits

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#59]
* [x] remove params from top level table
* [x] remove referer from top level table
* [x] if duration is > 1 minute round to nearest second
* [x] if duration is < 10 second round to 3 decimal places
* [x] date format '9/12/21, 19:22'  => '9 Dec 21, 19:22'
* [x] add table-sm to make it more compact
* [x] show the response codes wrapped in a bootstrap labels, 2xx in success, 3xx in info, 4xx and 5xx in warning / error

**Comment by jaypha** [comment]
I'll also add these
[] Fix breadcrumb displaying incorrect link when going to a profile from the 'recent' list.
[] Have delete code use require_sesskey()
[] Move profile settings to the Development/Excimer block.
