### ISSUE TITLE
Have admin options to auto save profiles which took more than X seconds

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#6]
Also have a sibling option which is to only keep the top N slowest profiles, so if the latest profile is not as slow as the top Nth profile then don't save it. If it is then save it and garbage collect the slowest one.

**Comment by nigelchapman-catalyst** [comment]
![image](https://user-images.githubusercontent.com/46659321/123026759-0bfb6980-d420-11eb-9dbc-df109db40c21.png)

Added to admin settings; confirmed working (e.g. set to 10 to record all, set to 60000 to record none). 

Second option will wait until profile table added in subsequent tickets.

**Comment by jaypha** [comment]
Some questions about N slowest.
If a profile is added manually by FLAMEME, is it subject to this test, or will it be always saved?
When the setting is changed, is there a callback or event that can be called to trim the profile table if N goes down?
Thanks

**Comment by brendanheywood** [comment]
No it will always be saved

**Comment by jaypha** [comment]
- [ ] Check number of saved profiles when updating settings
- [ ] unit tests
