### ISSUE TITLE
'Slowest' report should group by script and sort by max() of each script

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#60]
* [x] group by script

* [x] sort by worst stored
* [x] show a col with how many profiles we have for this script
* [x] created makes no sense, but possibly show the min / max of the date as a range instead, Earliest, Latest as two cols
* [ ] user might not make sense. But try this as a a group aggregation, eg 'Brendan (10), Jason (5)' meaning brendan did 10 profiles and jason did 5. This isn't critical so if its a pita just drop it
* [ ] response code, would be nice to keep it and do as an aggregation similar to above
* [x] make a new 'script detail' page which takes a script without wwwroot prefix as a param
* [x] this shows the subset of all profiles related to this script. This could possibly be one of the existing pages but with an optional ?script=foo filter

**Comment by jaypha** [comment]
Will probably want a way to expand out any script group and list the profiles.

**Comment by brendanheywood** [comment]
Yup added it to the list above

**Comment by jaypha** [comment]
- [ ] Delete by script

**Comment by jaypha** [comment]
I don't think having user and responsecode display this way is possible without a very complex SQL query. It would require returning a variable amount of values, which I do not know how to do.

The alternative would be to use `GROUP BY request, userid, responsecode`, and then reprocess the data in code before giving it to the table.

**Comment by jaypha** [comment]
user id and response code aggregates are to be removed due to version support issues.
