### ISSUE TITLE
Detect the type of the request eg document, image, css, script, 

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#61]
Broadly similar to what you see in the dev tools under the network tab. This doesn't need to be exhaustive the main thing is to tell apart the main html requests from other types.

Probably the cleanest is add fields for the content type, and then a second derived field based on content type 'group using moodles library here lib/classes/filetypes.php

**Comment by jaypha** [comment]
Is this perhaps moot, considering we cannot profile images, css files etc?

**Comment by brendanheywood** [comment]
No only theme files are in that camp there are still other files which we can deal with
