### ISSUE TITLE
Ajax, css, images don't seem to be getting profiled

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#62]
ie ramp down threshold to 0 ms and turn off caching in dev tools, I should get around ~24 requests profiled but I only see 4.

**Comment by jaypha** [comment]
I have discovered why this is occurring. In Moodle, there is a constant `ABORT_AFTER_CONFIG`. If this is set, then the usual setup (including calling plugin startup functions), is not performed. The comment in `lib/setup.php` says "_special support for highly optimised scripts that do not need libraries and DB connection_".

This setting is used in `/theme/image.php`, `/lib/javascript.php`, and many other such scripts. Therefore, these scripts are unprofilable.

**Comment by brendanheywood** [comment]
ok, lets just ignore this and move on
