### ISSUE TITLE
Enabling enable_auto setting causes exception to appear on every page load

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_excimer#68]
Enable auto profiling tool_excimer | enable_auto 

Enabling the above setting on a clean install causes the following warning to appear on subsequent page loads.

- Installed excimer using PECL steps.
- The excimer plugin was installed from an upgrade process of an existing site.

```
Exception calling 'tool_excimer_after_config'

    line 44 of /admin/tool/excimer/lib.php: call to tool_excimer\manager::init()
    line 1073 of /lib/setup.php: call to tool_excimer_after_config()
    line 82 of /config.php: call to require_once()
    line 26 of /user/files.php: call to require()
```

**Comment by brendanheywood** [comment]
Lets turn this into a 'this plugin must never be able to break moodle' issue. ie any sort of exception or condition inside excimer should gracefully just allow the normal request to continue.

**Comment by keevan** [comment]
The page does seem to load gracefully despite the exception message (see image below):

![image](https://user-images.githubusercontent.com/9924643/145927603-234ae42f-55e8-4930-9add-31e1d5b19e8d.png)

But yes it appears like the profiling isn't working due to the exception.

**Comment by keevan** [comment]
Worth mentioning that this is what it looks like on the container after installing if via PECL directly.

```
root@e1a658956028:/var/www/html# php -i | grep excimer
/usr/local/etc/php/conf.d/docker-php-ext-excimer.ini,
excimer
excimer support => enabled
excimer version => 1.0.2
```

Which is why the plugin install worked, but might be a docker php related issue where the extensions aren't enabled until maybe after a restart.
