### ISSUE TITLE
Have an admin option to purge old profiles after X days / weeks

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#7]
* [ ] have an option for a maximum number of profiles (default 100)
* [ ] have an option for a maximum age of profiles ( default 3 months)

**Comment by nigelchapman-catalyst** [comment]
Running php admin/cli/cron.php  is working now... Tested with a 2 hour timeout...

![image](https://user-images.githubusercontent.com/46659321/123200934-1176b380-d4f5-11eb-916d-0493b1a55598.png)

Before:

![image](https://user-images.githubusercontent.com/46659321/123200812-ce1c4500-d4f4-11eb-9cdf-8efcc6633836.png)

After:

![image](https://user-images.githubusercontent.com/46659321/123200892-f6a43f00-d4f4-11eb-9e6d-fdd35b5ec573.png)

**Comment by brendanheywood** [comment]
Moving this back to the backlog as it will need to be redone after the schema change
