### ISSUE TITLE
Add DONTFLAMEME option

### ISSUE THREAD

**Issue by jaypha** [catalyst/moodle-tool_excimer#75]
Adding `DONTFLAMEME` as a parameter should cause the profiler to **not** run, even when auto and `FLAMEALL` are set.
A question would be, if `DONTFLAMEME` is set, should profiling of all subrequests also be suppressed?

**Comment by brendanheywood** [comment]
What is the use case you have in mind for this? It sounds like more effort to not profile a page that it would be to delete it later or just ignore it and let it be cleaned up a some point.

**Comment by jaypha** [comment]
I find that when listing profiles, the list page gets added, which I find annoying. I add DONTFLAMEME and I can reload the page without the extra garbage being added.

**Comment by brendanheywood** [comment]
ok, I'm not opposed to it and if it help dev then go for it

I'm personally the opposite and am mostly using profiling the report pages

**Comment by brendanheywood** [comment]
> A question would be, if DONTFLAMEME is set, should profiling of all subrequests also be suppressed?

Probably not (yet), purely because detecting this is quite hard. This is the same problem as detecting the parent child relationships in https://github.com/catalyst/moodle-tool_excimer/issues/18 which we pushed back
