### ISSUE TITLE
Get github actions CI working 

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#8]
Example: https://github.com/catalyst/moodle-mod_applaunch/blob/main/.github/workflows/main.yml

**Comment by brendanheywood** [comment]
example:

https://github.com/catalyst/moodle-mod_applaunch/blob/main/.github/workflows/main.yml

**Comment by nigelchapman-catalyst** [comment]
CI Passing. 

![image](https://user-images.githubusercontent.com/46659321/123015262-47d80400-d40b-11eb-84a4-a069ab52119f.png)
