### ISSUE TITLE
refactor REASON_AUTO into REASON_SLOW

### ISSUE THREAD

**Issue by brendanheywood** [catalyst/moodle-tool_excimer#84]
REASON_SLOWTTFB
REASON_SLOWTOTAL
REASON_LONGTRANSACTION
REASON_READONLYSESSIONCANDIDATE
REASON_ETC

**Comment by jaypha** [comment]
I'm going to need more context on what each one means.

**Comment by brendanheywood** [comment]
Just rename the const from REASON_AUTO into REASON_SLOW, nothing more.

The reason being we will end up with multi reasons which are in some way 'automatic', the real reason we are keeping these types of profiles is not because they are automatic, but because they are slow. The task here is just the rename, the other consts were examples of potential future reasons to illustrate why we want to name it better.
