### ISSUE TITLE
Optimise flag checking

### ISSUE THREAD

**Issue by keevan** [catalyst/moodle-tool_excimer#91]
https://github.com/catalyst/moodle-tool_excimer/blob/e59bfac28d60e07f20c28ff43f97c604bb30c830/classes/manager.php#L49-L54

Potentially a microimprovement but one nonetheless, we could check $_REQUEST before doing the cookie/post/get checks as it might be there already.

https://stackoverflow.com/a/1924958

But not 100% sure, happy to get thoughts before proceeding. TIL about the cookie one so that one is somewhat unconfirmed.

**Comment by brendanheywood** [comment]
Not sure its worth worrying about too much

**Comment by jaypha** [comment]
By default, cookie is not included, so perhaps a better ordering would be REQUEST, COOKIE, env.
